name: Go

on: [push]

env:
  GO_VERSION: '1.23.3'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.6

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: go mod tidy
        run: |
          go mod tidy
          if [ -n "$(git status --porcelain)" ]; then
            echo "Run 'go mod tidy' and push it"
            exit 1
          fi
      - name: Unit tests
        run: go test -v ./...
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61